config/routes.rb
Rails.application.routes.draw do
  resources :ratings
  resources :students do
    collection do
      get :list
    end
  end
  
  get 'bootstrap/index'
  get 'bootstrap/FormPage'
  
  resources :orders do
    collection do
      get :list
    end
  end

  resources :products do
    collection do
      get :options
      get :totalprice      
    end
  end
  resources :categories

  match 'products/index' => 'products#index', via: [:get, :post]

  root 'products#index'

end

app/models/order.rb
class Order < ActiveRecord::Base
	has_many :products
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
    @order = Order.new
    @category = Category.all
    @product = Product.none          
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
        @order = Order.find(params[:id])
        #format.html { redirect_to orders_path, notice: 'Order was successfully created.' }
        render :json => @order
  end

  # GET /orders/new
  def new
    @order = Order.new
    @category = Category.all
    @product = Product.none    
  end

  # GET /orders/1/edit
  def edit
    @order = Order.find(params[:id])
    @category = Category.all
    @product = Product.none
    render :json => @order     
  end

  def list
    @orders = Order.all

    @myhash = []
    @orders.each do |index|
       @myhash << {id: index.id, quantity: index.quantity,totalprice: index.totalprice, category_name: Category.find(index.category_id).name,product_name: Product.find(index.product_id).name,price: Product.find(index.product_id).price}
    end

    render :json => @myhash
  end


  # POST /orders
  # POST /orders.json
  def create

    #@order = @product.Order.new(order_params)

    #@category = Category.find params[:category_dropdown]
    #@product = Product.find(params[:product_dropdown])

    @order = Order.new order_params.merge(category_id: params["category_dropdown"],
                                                               product_id: params["product_dropdown"])

    #@order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        #format.html { redirect_to orders_path, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params.merge(category_id: params["category_dropdown"],
                                                               product_id: params["product_dropdown"]))
        #format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      #format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:quantity, :totalprice)
    end
 
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :category, class: 'control-label' %><br>
    <%= select_tag "category_dropdown", options_from_collection_for_select(@category, "id", "name"), include_blank: true, class: 'form-control'  %>    
  </div>  

  <div class="form-group">
  <div id="anshuman">
      <%= f.label :product, class: 'control-label'  %><br>
    <%= select_tag "product_dropdown", options_from_collection_for_select(@product, "id", "name"), include_blank: true, class: 'form-control'  %>        
    </div>  
</div>

  <div class="form-group">
    <%= f.label :quantity, class: 'control-label' %><br>
    <%= f.text_field :quantity, class: 'form-control' %>
    <span class="help-block"></span>
  </div>

  <div class="form-group">
    <div id="anshuman1">
    <%= f.label :totalprice, class: 'control-label' %><br>
    <%= f.number_field :totalprice, class: 'form-control' %>
  </div>
  </div>

  <div class="actions">
    <%= f.submit "Create Order", class: 'btn btn-default', id: 'btnCreateOrder'%>
    <%= f.submit "Update Order", class: 'btn btn-default', id: 'btnUpdateOrder',style:'display:none;' %>
  </div>
<input type="text" name="orderId" id="txtorderId">
<% end %>

<script>
/*$(document).ready(function(){

      $("#new_order").submit(function(e) {
        //alert("hello");
        var url = "/orders"; // the script where you handle the form input.

    $.ajax({
           type: "POST",
           url: url,
           data: $("#new_order").serialize(), // serializes the form's elements.
           success: function(data)
           {
              //alert(data); // show response from the php script.
              opener.listOrders();
              window.close();

           }
         });
    e.preventDefault();

});
});


        //alert("Submitted");

  var order_url = "/orders/list";

  $.ajax({
    //options.async = true;
    url: order_url,
    type: 'get',
    success: function(data) {
        if(data!=null && data.length>0){
          window.opener.$("#orderlist").html('');
          $.each(data,function(index,key){
            alert(index);
            window.opener.$("#orderlist").append("<tr><td>"+key.quantity+"</td><td>"+key.totalprice+"</td><td colspan=3>Action</td></tr>");
            //$("#product_dropdown").append("<option value='"+key.id+"'>"+key.name+"</option>");
          })
              window.close();}
            }
  });
              //opener.CallParent();
              //window.close();
});*/
</script>

<script type="text/javascript" async="async">
  $('#category_dropdown').change(function() {
  //alert("Hello");

  var product_url = "/products/options";
  //alert(product_url);
  var product_select = $(this).next('select');
  //alert(product_select);

//debugger;

  $.ajax({
    //options.async = true;
    data:{category_id:$("#category_dropdown").val()},
    url: product_url,
    async:false,  
    type: 'get',
    success: function(data) {
        $("#product_dropdown").empty();
        if(data!=null && data.length>0){
          $.each(data,function(index,key){
            $("#product_dropdown").append("<option value='"+key.id+"'>"+key.name+"</option>");
          })
        }
      //$("#anshuman").html(data);

      //$(document.body).html(data);
    }
  });
});

</script>

<script type="text/javascript">
    $('#order_quantity').change(function() {

  var product_url1 = "/products/totalprice?product_dropdown=" + $('#product_dropdown').val() + '&order_quantity=' + $('#order_quantity').val();
  //alert(product_url1);
  var product_input = $(this).next('input');

 $.ajax({
    //options.async = true;
    url: product_url1,
    method: 'get',
    success: function(data) {
    //alert(data);
    //$('#anshuman1').html(data);
   
        //$("#order_totalprice").empty();
        if(data!=null){
          //alert(data);
          $("#order_totalprice").val(data);
        }
      //$(document.body).html(data);
    }
  });

});

</script>

app/views/orders/_table_row.html.erb
<% @orders.each do |order| %>
	<tr>
		<td><%= order.quantity %></td>
		<td><%= order.totalprice %></td>
		<td><%= link_to 'Show', order, remote: true %></td>
		<td><%= link_to 'Edit', edit_order_path(order), remote: true %></td>
		<td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' }, remote: true %></td>
	</tr>
<% end %>   

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
<h1>Listing Orders</h1>

<table id="order" class="table table-striped" border="1">
  <thead>
    <tr>
      <th>Category</th>
      <th>Product</th> 
      <th>Unit Price</th>              
      <th>Quantity</th>
      <th>Total Price</th>
      <th colspan="3"><center>Action</center></th>
    </tr>
  </thead>

  <tbody id="orderlist">
          
  </tbody>
</table>

<br>

<div class="form-group" id="formdiv"></div>

<%# Added Bootstrap data modal attribute %>
<%= link_to 'New Order', '#new_order_modal', 'data-toggle' => 'modal' %>

<%# Bootstrap modal markup. @see: http://getbootstrap.com/javascript/#modals %>
<div class="modal fade" id="new_order_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabelCreate">Create Order</h4>
        <h4 class="modal-title" id="myModalLabelEdit" style="display:none;">Edit Order</h4>
      </div>
      <div class="modal-body">
        <%# Render the new person form (passing modal => true to enable remote => true) %>
        <%= render 'form' %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>


<script>
$(document).ready(function(){

              
      $("#btnCreateOrder").click(function(e) {
        //alert("data");
        
        var url = "/orders"; // the script where you handle the form input.

    $.ajax({
           type: "POST",
           url: url,
           data: $("#new_order").serialize(), // serializes the form's elements.
           success: function(data)
           {
              //alert("Hello");
              $('#new_order_modal').modal('hide');

              listOrders();
              //window.close();
              //$.modal.close();
          

           }
         });
e.preventDefault(); 

});


      $("#btnUpdateOrder").click(function(e) {

        
        var url = "/orders/"+$("#txtorderId").val(); // the script where you handle the form input.

        alert(url);
    $.ajax({
           type: "PATCH",
           url: url,
           data: $("#new_order").serialize(), // serializes the form's elements.
           success: function(data)
           {
              //alert("Hello");
              $('#new_order_modal').modal('hide');

              listOrders();
              $('#myModalLabelCreate').show();
              $('#myModalLabelEdit').hide();    

              $('#btnCreateOrder').show();
              $('#btnUpdateOrder').hide();                  
              //window.close();
              //$.modal.close();

           }
         });
e.preventDefault(); 

});
});
</script>


<script type="text/javascript">
  $(function(){
      listOrders();
  });

  function listOrders() {

     var order_url = "/orders/list";

      $.ajax({
        //options.async = true;
        url: order_url,
        type: 'get',
        success: function(data) {
            if(data!=null && data.length>0){
              $("#orderlist").html('');
              $.each(data,function(index,key){
                //alert(index);
                $("#orderlist").append("<tr><td>"+key.category_name+"</td><td>"+key.product_name+"</td><td>"+key.price+"</td><td>"+key.quantity+"</td><td>"+key.totalprice+"</td><td><span onclick=ShowOrder("+key.id+")>Show</span></td><td><span onclick=EditOrder("+key.id+") data-toggle='modal' data-target='#new_order_modal'>Edit</span></td><td><span onclick=DeleteOrder("+key.id+")>Destroy</span></td></tr>");

              })

                  }
                }
      });
}
function EditOrder(orderId){
  alert(orderId);

     var edit_url = "/orders/"+orderId+"/edit";

      $.ajax({
        //options.async = true;
        url: edit_url,
        type: 'get',
        success: function(data) {
            if(data!=null){ 
                //$("#new_order_modal").modal("show");
                $('#myModalLabelCreate').hide();
                $('#myModalLabelEdit').show();    

                $('#btnCreateOrder').hide();
                $('#btnUpdateOrder').show();    

                $("#category_dropdown").val(data.category_id);
                $("#category_dropdown").trigger("change");
                $("#product_dropdown").val(data.product_id);
                $("#order_quantity").val(data.quantity);
                $("#order_totalprice").val(data.totalprice);
                $("#txtorderId").val(orderId);
            }
        }
      });  
}
function DeleteOrder(orderId){
  //alert(orderId);

     var delete_url = "/orders/"+orderId;

      $.ajax({
        url: delete_url,
        type: 'delete',
        success: function(data) {
              //alert("data");
              listOrders();

               }
      });  
}
function ShowOrder(orderId){
  alert(orderId);

     var show_url = "/orders/"+orderId;

      $.ajax({
        //options.async = true;
        url: show_url,
        type: 'get',
        success: function(data) {
            //alert("data");
            //alert(data);            
            if(data!=null){
              //$("#orderlist").html('');
                //alert(data);
                $("#formdiv").html('<p><strong>Quantity:</strong>'+data.quantity+'</p><p><strong>Totalprice:</strong>'+data.totalprice+'</p><p><strong>ID:</strong>'+data.id+'</p><p><span onclick=EditOrder('+data.id+') data-toggle="modal" data-target="#new_order_modal">Edit</span>&nbsp;|&nbsp;<span onclick="clearDiv()">Back</span>');
                  }
                }
      });  
}

function clearDiv(){
  $("#formdiv").html('');
}
</script>

<br><br>
<%= link_to 'New Order', new_order_path, :onclick=>"window.open(this.href,'New Order', 'height=600, width=600');return false;" 
%>
</div>

app/views/orders/list.html.erb
<div class="container">
<h1>Listing Orders</h1>

<table id="order" class="table table-striped" border="1">
  <thead>
    <tr>
      <th>Category</th>
      <th>Product</th>  
      <th>Unit Price</th>  
      <th>Quantity</th>
      <th>Total Price</th>
      <th colspan="3"><center>Action</center></th>
    </tr>
  </thead>

  <tbody id="orderlist">

<% @orders.each do |order| %>
	<tr>
		<td><%= Category.find(order.category_id).name %></td>
		<td><%= Product.find(order.product_id).name %></td>
    <td><%= Product.find(order.product_id).price %></td>
		<td><%= order.quantity %></td>
		<td><%= order.totalprice %></td>
		<td><%= link_to 'Show', order, remote: true %></td>
		<td><%= link_to 'Edit', edit_order_path(order), remote: true %></td>
		<td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' }, remote: true %></td>
	</tr>
<% end %>   

  </tbody>
</table>

</div>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form' %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Quantity:</strong>
  <%= @order.quantity %>
</p>

<p>
  <strong>Totalprice:</strong>
  <%= @order.totalprice %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>