config/routes.rb
Rails.application.routes.draw do
  resources :ratings
  resources :students do
    collection do
      get :list
    end
  end
  
  get 'bootstrap/index'
  get 'bootstrap/FormPage'
  
  resources :orders do
    collection do
      get :list
    end
  end

  resources :products do
    collection do
      get :options
      get :totalprice      
    end
  end
  resources :categories

  match 'products/index' => 'products#index', via: [:get, :post]

  root 'products#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :products, dependent: :destroy
	accepts_nested_attributes_for :products, :reject_if => lambda {|product| product[:name].blank?}, :allow_destroy => true

	validates :name, presence: { message: "%{model} %{attribute} must be given please" }
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
        @product = @category.products
  end

  # GET /categories/new
  def new
    @category = Category.new
    #3.times do
   # @products = []
      @products = @category.products.build
    #end
  end

  # GET /categories/1/edit
  def edit

  end

  # POST /categories
  # POST /categories.json
  def create
    binding.pry

    #if params[:category][:product].present?
    
    #else

      @category = Category.new(category_params)
    #end

    respond_to do |format|
      if @category.save

        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    #binding.pry
    @product = @category.update(category_params)   
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      #params.require(:category).permit(:name)
      #params.require(:category).permit(:name, :products_attributes => [:name, :price])
      #binding.pry    
      #if params[:commit] == "Update Category"
      params.require(:category).permit(:name, :products_attributes => [:name , :price, :id , :destroy])
      #else
      #params.require(:category).permit(:name, :products_attributes => [:name, :price])
      #end
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <!--<h1>Add Product</h1>-->

  <%= f.fields_for :products do |p| %>

  <% #render :partial => "products", :locals => {products: p} %>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script>
$(document).ready(function(){
   $('a').click(function(){
      $('#mydiv1').append('<div class=field><%= p.label :name %><br><%= p.text_field :name, multiple: true %></div><div class=field><%= p.label :price %><br><%= p.text_field :price, multiple: true %></div><div class=field><%= p.check_box :_destroy, multiple: true %><br><%= p.label :_destroy, 'Remove Product' %></div>');

      $('#mydiv1').show();
   });
});
</script>

<p><a href="javasctipt:void(0)" id="a">Add Product</a></p>

<div id="mydiv1" style="display:none">

</div>

  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>  
<% end %>

app/views/categories/_products.html.erb
<div class="add_form">
	<div class="field">
		<%= products.label :name %><br>
		<%= products.text_field :name %>
	</div>
	<div class="field">
		<%= products.label :price %><br>
		<%= products.text_field :price %>
	</div>
	<div class="field">
		<%= products.check_box :_destroy %><br>
		<%= products.label :_destroy, "Remove Product" %>
	</div>
</div>	

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= link_to 'Show', category %> | </td>
        <td><%= link_to 'Edit', edit_category_path(category) %> | </td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %> | </td>
        <td><%= link_to 'Add Product', new_product_path(:category_id => category) %> | </td>
        <td><%= link_to 'Add Product (New Window)', new_product_path(:category_id => category), :onclick=>"window.open(this.href,'Create Product', 'height=400, width=400');return false;" %></td>  
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
  <h1>Product List</h1>  
<table width="40%">
    <% @product.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.price %></td>
        <td><%= product.category.name if product.category.present? %></td>
      </tr>
    <% end %>
</table>

</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>